### ISSUE TITLE
Cannot login after signup

### ISSUE THREAD

**Issue by Coalpha** [legodude17/crasher#3]
Steps to reproduce:
- Login
- Logout
- Login

Feel Pain
![image](https://user-images.githubusercontent.com/22552895/49693622-e3931480-fb2c-11e8-8a3a-77d194936d93.png)

**Comment by Coalpha** [comment]
I actually have no idea what's going on so can you fix this since I have to do the ~~pain~~ styles?

**Comment by legodude17** [comment]
You fixed it good jobb.

**Comment by Coalpha** [comment]
oh nO

**Comment by Coalpha** [comment]
Removed `putUser` call without passing callback argument
